select veiculo.placa
      ,veiculo.grupo
      ,veiculo.empresa
      ,veiculo.filial
      ,veiculo.empresalocado
      ,veiculo.filiallocado
      ,veiculo.unidadelocado
      ,veiculo.dtinc
      ,veiculo.dtalt
      ,veiculo.ativoinativo
      ,veiculo.proprietario
      ,veiculo.podesercoligado
      ,veiculo.tipofrota
      ,veiculo.numerofrota
      ,veiculo.tipoveiculo
      ,veiculo.marcaveiculo
      ,veiculo.modeloveiculo
      ,veiculo.utilizacaoveiculo
      ,veiculo.atividadeveiculo
      ,veiculo.tipocargaveiculo
      ,veiculo.caracteristicaveiculo
      ,veiculo.carroceriaveiculo
      ,veiculo.anofabricacao
      ,veiculo.anomodelo
      ,veiculo.anofabricacaocarroceria
      ,veiculo.numerochassi
      ,veiculo.numeromotor
      ,veiculo.numerodiferencial
      ,veiculo.numerocaixa
      ,veiculo.patrimonio
      ,veiculo.codigorenavam
      ,veiculo.codigodetran
      ,veiculo.paisemplacamento
      ,veiculo.ufemplacamento
      ,veiculo.cidadeemplacamento
      ,veiculo.corcabine
      ,veiculo.corcarroceria
      ,veiculo.combustivelgasolina
      ,veiculo.combustivelalcool
      ,veiculo.combustivelgas
      ,veiculo.combustiveldiesel
      ,veiculo.combustivelquerosene
      ,veiculo.combustiveleletricidade
      ,veiculo.rebocador
      ,veiculo.rebocado
      ,veiculo.quantidadeestepes
      ,veiculo.mediaconsumofabrica
      ,veiculo.observacao
      ,veiculo.tipomarcador
      ,veiculo.tara
      ,veiculo.capacidadecarga
      ,veiculo.permissionaria
      ,veiculo.alienacaofiduciaria
      ,veiculo.cnpjcpfcodigorastreador
      ,veiculo.vinculorastreador
      ,veiculo.numeroantena
      ,veiculo.trajeto
      ,veiculo.capacidadem3
      ,veiculo.centrocusto
      ,veiculo.utilizarcontacorrente
      ,veiculo.mediahistorica
      ,veiculo.mediarodadovazio
      ,veiculo.possuirefrigeracao
      ,veiculo.tipomarcadorrefrigeracao
      ,veiculo.mediaconsumofabricarefrigeracao
      ,veiculo.combustivelgasolinarefrigeracao
      ,veiculo.combustivelgasrefrigeracao
      ,veiculo.combustivelquerosenerefrigeracao
      ,veiculo.combustivelalcoolrefrigeracao
      ,veiculo.combustiveldieselrefrigeracao
      ,veiculo.combustiveleletricidaderefrigeracao
      ,veiculo.possuimotor
      ,veiculo.capacidadetanque
      ,veiculo.emblemado
      ,veiculo.fixotransportadora
      ,veiculo.codigocontarastreadora
      ,veiculo.integrarposicionamentorastreadora
      ,veiculo.efetuacoleta
      ,veiculo.congelamento
      ,veiculo.bitrem
      ,veiculo.dtinativo
      ,veiculo.situacaoveiculorastreamento
      ,veiculo.funcionarioresponsavel
      ,veiculo.gruporastreador
      ,veiculo.empresarastreador
      ,veiculo.enderecowebrastreamentoveiculo
      ,veiculo.usuariorastreamentowebveiculo
      ,veiculo.senharastreamentowebveiculo
      ,veiculo.nomeultimagerenciadorarisco
      ,veiculo.foneultimagerenciadorarisco
      ,veiculo.quantidadedigitosmarcador
      ,veiculo.quantidadedigitosmarcadorrefrigeracao
      ,veiculo.contagemmarcador
      ,veiculo.contagemmarcadorrefrigeracao
      ,veiculo.marcacaorodadaimplantacao
      ,veiculo.marcacaorodadasistema
      ,veiculo.marcacaorodadatotal
      ,veiculo.marcacaorodadaimplantacaorefrigeracao
      ,veiculo.marcacaorodadasistemarefrigeracao
      ,veiculo.marcacaorodadatotalrefrigeracao
      ,veiculo.contagemmarcadoratualizoumarcacaorodadasistema
      ,veiculo.marcadoratualizoumarcacaorodadasistema
      ,veiculo.contagemmarcadoratualizoumarcacaorodadasistemarefrigeracao
      ,veiculo.marcadoratualizoumarcacaorodadasistemarefrigeracao
      ,veiculo.placatemporaria
      ,veiculo.dtentrada
      ,veiculo.numeronotafiscal
      ,veiculo.fornecedornotafiscal
      ,veiculo.levantareixo
      ,veiculo.reduzido
      ,veiculo.cnpjcpfcodigocontrato
      ,veiculo.razaosocialcontrato
      ,veiculo.atividadeveiculocontrato
      ,veiculo.situacaocontrato
      ,veiculo.numerocontrato
      ,veiculo.dtvigenciacontrato
      ,veiculo.tipocontrato
      ,veiculo.valortetodescontocontrato
      ,veiculo.dtinativocontrato
      ,veiculo.percvalorcontrato
      ,veiculo.usuariomarkquestionario
      ,veiculo.tecnologiarastreadora
      ,veiculo.semaforo
      ,veiculo.recebeadiantamento
      ,veiculo.utilizareagentecombustivel
      ,veiculo.utilizareagentecombustivelregrigeracao
      ,veiculo.dtinicioacertoafretamento
      ,veiculo.dtultimaposicaorastreador
      ,veiculo.dtultimaocorrenciarastreador
      ,veiculo.idcorveiculocabine
      ,veiculo.idcorveiculocarroceria
      ,veiculo.sensortemperatura1
      ,veiculo.sensortemperatura2
      ,veiculo.sensortemperatura3
      ,veiculo.dtemissaocrv
      ,veiculo.idtipocomunicacaorastreador
      ,veiculo.rastreadormovel
      ,veiculo.placaanterior
      ,veiculo.idrastreadoramodelorastreador
      ,veiculo.consumomdioarla
      ,veiculo.capacidadetanquearla
      ,veiculo.possuiarla
      ,veiculo.tipomarcadorarla
      ,veiculo.quantidadedigitosmarcadorarla
      ,veiculo.contagemmarcadorarla
      ,veiculo.capacidadetanquerefrigeracao
      ,veiculo.tipocarga
      ,veiculo.grupotiponegocio
      ,veiculo.valorfipe
      ,veiculo.quantidadeeixoslevantados
      ,veiculo.dttrocaplaca
      ,veiculo.integrartelemetriarastreadora
      ,veiculo.possuihubodometro
      ,veiculo.quantidadedigitosmarcadorhubodometro
      ,veiculo.contagemmarcadorhubodometro
      ,veiculo.marcacaorodadaimplantacaohubodometro
      ,veiculo.possuivinculoanttfiliallocado
      ,veiculo.escolta
      ,veiculo.cnpjcpfcodigoempresaescolta
      ,veiculo.cnpjcpfcodigoadministradora
      ,veiculo.codigoadministradoravalepedagio
      ,veiculo.idforpagvalepedag
      ,veiculo.tipofavorecidovalepedagio
      ,veiculo.idgerenciadoratemperatura
      ,veiculo.capacidadealtura
      ,veiculo.capacidadecomprimento
      ,veiculo.capacidadelargura
      ,veiculo.apisulcontrolaposicaoveiculo,
      caracteristicaveiculo.descricao as caracteristicadescricao,
      tipoveiculo.descricao as tipoveiculodescricao
from veiculo, caracteristicaveiculo, tipoveiculo
where veiculo.tipoveiculo = tipoveiculo.codigo and veiculo.caracteristicaveiculo = caracteristicaveiculo.codigo